"""
Artifact loading utilities for the NYC Business Survival Streamlit app.

This module centralizes loading of trained model artifacts and reference
datasets used by the application. Artifacts include serialized model
pipelines, feature metadata, evaluation summaries, and reference datasets
used for simulation and visualization.

The artifacts are generated by the model training pipelines and stored in
the `artifacts/` directory. These functions load the required objects and
cache them using Streamlit's caching utilities to avoid repeated disk I/O
and improve application performance.

Supported models:
- Logistic regression model for 36-month survival prediction
- Standard Cox proportional hazards survival model
- Time-varying Cox survival model
"""

from __future__ import annotations

import json
import pickle
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st


APP_DIR = Path(__file__).resolve().parents[1]
ARTIFACT_DIR = APP_DIR / "artifacts"

LOGISTIC_DIR = ARTIFACT_DIR / "logistic"
COX_STANDARD_DIR = ARTIFACT_DIR / "cox_standard"
COX_TIME_VARYING_DIR = ARTIFACT_DIR / "cox_time_varying"


def _load_pickle(path: Path) -> Any:
    """
    Load a pickled artifact from disk.

    Parameters:
    path : Path
        File path to the pickle artifact.

    Returns:
    Any
        The deserialized Python object stored in the pickle file.

    Raises:
    FileNotFoundError
        If the specified artifact file does not exist.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Expected artifact not found: {path}\n"
            f"Contents of parent directory: {[p.name for p in path.parent.glob('*')]}"
        )
    with path.open("rb") as file_obj:
        return pickle.load(file_obj)


@st.cache_resource
def load_logistic_artifacts() -> dict[str, Any]:
    """
    Load trained logistic regression model artifacts.

    Returns:
    dict[str, Any]
        Dictionary containing:
        - pipeline : trained sklearn pipeline
        - kept_columns : feature columns used by the model
        - dropped_columns : features removed during preprocessing
        - coef_summary : dataframe of logistic regression coefficients
        - metrics : evaluation metrics from model testing
    """
    return {
        "pipeline": _load_pickle(LOGISTIC_DIR / "logistic_pipeline.pkl"),
        "kept_columns": _load_pickle(LOGISTIC_DIR / "logistic_kept_columns.pkl"),
        "dropped_columns": _load_pickle(LOGISTIC_DIR / "logistic_dropped_columns.pkl"),
        "coef_summary": pd.read_csv(LOGISTIC_DIR / "logistic_coefficient_summary.csv"),
        "metrics": json.loads(
            (LOGISTIC_DIR / "logistic_evaluation_metrics.json").read_text(
                encoding="utf-8"
            )
        ),
    }


@st.cache_data
def load_logistic_reference_data() -> dict[str, pd.DataFrame]:
    """
    Load reference datasets used for logistic model evaluation and simulation.

    These datasets provide the feature distributions used by the Streamlit
    interface to construct baseline profiles and contextual comparisons.

    Returns:
    dict[str, pd.DataFrame]
        Dictionary containing:
        - businesses : full balanced business survival dataset
        - x_train : training feature matrix used during model training
        - x_test : testing feature matrix used for evaluation
    """
    return {
        "businesses": pd.read_csv(LOGISTIC_DIR / "business_survival_balanced_dataset.csv"),
        "x_train": pd.read_csv(LOGISTIC_DIR / "X_train_balanced_split.csv"),
        "x_test": pd.read_csv(LOGISTIC_DIR / "X_test_balanced_split.csv"),
    }


@st.cache_resource
def load_standard_cox_artifacts() -> dict[str, Any]:
    """
    Load artifacts for the standard Cox proportional hazards model.

    Returns:
    dict[str, Any]
        Dictionary containing:
        - model : trained CoxPH model
        - scaler : fitted feature scaler used during training
        - kept_columns : features retained in the final model
        - dropped_columns : features removed during preprocessing
        - summary : coefficient summary table for the Cox model
    """
    return {
        "model": _load_pickle(COX_STANDARD_DIR / "coxph_model.pkl"),
        "scaler": _load_pickle(COX_STANDARD_DIR / "coxph_scaler.pkl"),
        "kept_columns": _load_pickle(COX_STANDARD_DIR / "coxph_kept_columns.pkl"),
        "dropped_columns": _load_pickle(COX_STANDARD_DIR / "coxph_dropped_columns.pkl"),
        "summary": pd.read_csv(COX_STANDARD_DIR / "coxph_summary.csv"),
    }


@st.cache_resource
def load_time_varying_cox_artifacts() -> dict[str, Any]:
    """
    Load artifacts for the time-varying Cox survival model.

    Returns:
    dict[str, Any]
        Dictionary containing:
        - model : trained Cox time-varying survival model
        - scaler : fitted feature scaler
        - kept_columns : features used by the model
        - dropped_columns : removed features
        - summary : coefficient summary table
    """
    return {
        "model": _load_pickle(COX_TIME_VARYING_DIR / "cox_time_varying_model.pkl"),
        "scaler": _load_pickle(COX_TIME_VARYING_DIR / "cox_time_varying_scaler.pkl"),
        "kept_columns": _load_pickle(
            COX_TIME_VARYING_DIR / "cox_time_varying_kept_columns.pkl"
        ),
        "dropped_columns": _load_pickle(
            COX_TIME_VARYING_DIR / "cox_time_varying_dropped_columns.pkl"
        ),
        "summary": pd.read_csv(COX_TIME_VARYING_DIR / "cox_time_varying_summary.csv"),
    }
